// `npm run email:build` (BUILD F-5, FR-28, FR-29, D7): renders the auth email templates with
// react-email and writes them where Supabase reads them (config.toml [auth.email.template.*]).
// The output is committed; CI re-runs this and fails on any difference (templates in sync).
// Exits 1 unless each file keeps GoTrue's {{ .TokenHash }} and {{ .SiteURL }} placeholders.
import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const out = resolve(root, ".email-out");
const target = resolve(root, "supabase/templates");

// template file in src/emails → [the name config.toml points at, the link type it must carry]
const MAP = {
  "verify-email": ["confirmation", "signup"],
  "magic-link": ["magic_link", "magiclink"],
  "reset-password": ["recovery", "recovery"],
};
// The link itself must survive rendering (the logo URL alone would satisfy a looser check).
const link = (type) =>
  `href="{{ .SiteURL }}/auth/confirm?token_hash={{ .TokenHash }}&amp;type=${type}"`;
// After the doctype: anything before it puts older mail clients (Outlook) in quirks mode.
const NOTE =
  "<!-- Generated by `npm run email:build` from src/emails. Do not edit: change the template or src/config/app.ts and rebuild. -->";

rmSync(out, { recursive: true, force: true });
execFileSync(
  resolve(root, "node_modules/.bin/email"),
  ["export", "--dir", "src/emails", "--outDir", ".email-out", "--silent"],
  { cwd: root, stdio: "inherit" },
);

// Check every template first, then write all or none (no half-updated set).
const built = [];
let failed = false;
for (const [source, [name, type]] of Object.entries(MAP)) {
  const html = readFileSync(resolve(out, `${source}.html`), "utf8");
  if (!html.includes(link(type))) {
    console.error(`email:build: ${source} has no ${link(type)}`);
    failed = true;
    continue;
  }
  const withNote = html.replace(/^(<!DOCTYPE[^>]*>)/i, `$1${NOTE}`);
  if (withNote === html) {
    console.error(`email:build: ${source} doesn't start with a doctype`);
    failed = true;
    continue;
  }
  built.push([name, withNote]);
}
rmSync(out, { recursive: true, force: true });
if (failed) process.exit(1);
mkdirSync(target, { recursive: true });
for (const [name, html] of built) {
  writeFileSync(resolve(target, `${name}.html`), html + "\n");
  console.log(`email:build: supabase/templates/${name}.html`);
}
